controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
  - name: end_eff_controller
    action_ns: gripper_action
    type: GripperCommand
    default: True
    joints:
      - joint5
      - joint6