DATA SEGMENT
    ORG 1000H
    RADIUS DD 3.3
    CONST DD 1.33
    VOLUME DD 01 DUP(?)
DATA ENDS
CODE SEGMENT
ASSUME CS:CODE,DS:DATA
    .8087
    START:
    MOV AX,DATA
    MOV DS,AX
    FINIT
    FLD RADIUS
    FST ST(4)
    FMUL ST(0),ST(4)
    FMUL ST(0),ST(4)
    FLD CONST
    FMUL
    FLDPI
    FMUL
    FST VOLUME
    HLT
    CODE ENDS
END START