DATA SEGMENT
    ORG 1000H
    RADIUS DD 1.3
    HEIGHT DD 1.7
    CONSTANT DD 0.33
    VOLUME DD 01 DUP(?)
DATA ENDS
CODE SEGMENT
ASSUME CS:CODE,DS:DATA
    .8087
    START:
    MOV AX,DATA
    MOV DS,AX
    FINIT
    FLD RADIUS
    FST ST(2)
    FMUL ST(0),ST(2)
    FLD HEIGHT
    FMUL ST(0),ST(1)
    FLD CONSTANT
    FMUL ST(0),ST(1)
    FLDPI
    FMUL
    FST VOLUME
    HLT
    CODE ENDS
END START