DATA SEGMENT
    MSG1 DB 10,13,'ENTER ANY STRING: $'
    MSG2 DB 10,13,'ENTERED STRING IS: $'
    MSG4 DB 10,13,'NO GIVEN STRING IS NOT A PALINDROME $'
    MSG5 DB 10,13,'THE GIVEN STRING IS A PALINDROME $'
    P1 LABEL BYTE
    M1 DB 0FFFH
    L1 DB ?
    P11 DB 00FFH DUP('$')
    P22 DB 00FFH DUP('$'0)
DATA ENDS
DISPLAY MACRO MSG
    MOV AH,9
    LEA DX,MSG
    INT 21H
ENDM
CODE SEGMENTASSUME CS:CODE,DS:DATA
START:
MOV AX,DATA
MOV DS,AX
DISPLAY MSG1
LEA DX,P1
MOV AH,0AH
INT 21H
DISPLAY MSG2
DISPALY P11
MOV DL,L1
ADD DL,30H
MOV AH,2
INT 21H

DISPLAY MSG6
LEA S1,P1